# This is a workflow to compile the cmeps source without cime
name: extbuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-cmeps:
    runs-on: ubuntu-latest
    env:
      CC: mpicc
      FC: mpifort
      CXX: mpicxx
      CPPFLAGS: "-I/usr/include -I/usr/local/include"
      # Versions of all dependencies can be updated here
      ESMF_VERSION: v8.4.0
      PNETCDF_VERSION: checkpoint.1.12.3
      NETCDF_FORTRAN_VERSION: v4.6.0
      PIO_VERSION: pio2_5_10
    steps:
      - uses: actions/checkout@v3
        # Build the ESMF library, if the cache contains a previous build
        # it will be used instead
      - id: load-env
        run: |
          sudo apt-get update
          sudo apt-get update
          sudo apt-get install gfortran
          sudo apt-get install wget
          sudo apt-get install openmpi-bin libopenmpi-dev
          sudo apt-get install netcdf-bin libnetcdf-dev libnetcdff-dev
          sudo apt-get install pnetcdf-bin libpnetcdf-dev
          sudo apt-get install autotools-dev autoconf
      - id: cache-esmf
        uses: actions/cache@v3
        with:
          path: ~/ESMF
          key: ${{ runner.os }}-${{ env.ESMF_VERSION }}-ESMF
      - name: Cache ParallelIO
        id: cache-ParallelIO
        uses: actions/cache@v3
        with:
          path: ~/pio
          key: ${{ runner.os }}-${{ env.PIO_VERSION }}.pio
      - name: Build ParallelIO
        if: steps.cache-ParallelIO.outputs.cache-hit != 'true'
        uses: NCAR/ParallelIO/.github/actions/parallelio_cmake@9390e30e29d4ebbfbef0fc72162cacd9e8f25e4e
        with:
          parallelio_version: ${{ env.ParallelIO_VERSION }}
          enable_fortran: True
          install_prefix: $HOME/pio
      - name: Build ESMF
        if: steps.cache-esmf.outputs.cache-hit != 'true'
        uses: ESCOMP/CDEPS/.github/actions/buildesmf@e06246b560d3132170bb1a5443fa3d65dfbd2040
        with:
          esmf_version: ${{ env.ESMF_VERSION }}
          esmf_bopt: g
          esmf_comm: openmpi
          install_prefix: $HOME/ESMF
          netcdf_c_path: /usr
          netcdf_fortran_path: /usr
          pnetcdf_path: /usr
          parallelio_path: $HOME/pio
      - name: Build CMEPS
        run: |
          export ESMFMKFILE=$HOME/ESMF/lib/libg/Linux.gfortran.64.openmpi.default/esmf.mk
          export PIO=$HOME/pio
          mkdir build-cmeps
          pushd build-cmeps
          cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_Fortran_FLAGS="-g -Wall -Werror -ffree-form -ffree-line-length-none  -Wno-unused-dummy-argument" ../
          make VERBOSE=1
          popd
